<?php
/**
 * @package      Crowdfunding
 * @subpackage   Components
 * @author       Todor Iliev
 * @copyright    Copyright (C) 2015 Todor Iliev <todor@itprism.com>. All rights reserved.
 * @license      http://www.gnu.org/copyleft/gpl.html GNU/GPL
 */

// no direct access
defined('_JEXEC') or die;

class CrowdfundingModelImport extends JModelForm
{
    protected function populateState()
    {
        $app = JFactory::getApplication();
        /** @var $app JApplicationAdministrator */

        // Load the filter state.
        $value = $app->getUserStateFromRequest('import.context', 'type', "currencies");
        $this->setState('import.context', $value);
    }

    /**
     * Method to get the record form.
     *
     * @param   array   $data     An optional array of data for the form to interrogate.
     * @param   boolean $loadData True if the form is to load its own data (default case), false if not.
     *
     * @return  JForm   A JForm object on success, false on failure
     * @since   1.6
     */
    public function getForm($data = array(), $loadData = true)
    {
        // Get the form.
        $form = $this->loadForm($this->option . '.import', 'import', array('control' => 'jform', 'load_data' => $loadData));
        if (empty($form)) {
            return false;
        }

        return $form;
    }

    /**
     * Method to get the data that should be injected in the form.
     *
     * @return  mixed   The data for the form.
     * @since   1.6
     */
    protected function loadFormData()
    {
        // Check the session for previously entered form data.
        $data = JFactory::getApplication()->getUserState($this->option . '.edit.import.data', array());

        return $data;
    }

    public function extractFile($file, $destFolder)
    {
        // extract type
        $zipAdapter = JArchive::getAdapter('zip');
        $zipAdapter->extract($file, $destFolder);

        $dir = new DirectoryIterator($destFolder);

        $fileName = JFile::stripExt(basename($file));

        $filePath = "";

        foreach ($dir as $fileinfo) {

            $currentFileName = JFile::stripExt($fileinfo->getFilename());
            if (!$fileinfo->isDot() and strcmp($fileName, $currentFileName) == 0) {
                $filePath = $destFolder . DIRECTORY_SEPARATOR . JFile::makeSafe($fileinfo->getFilename());
                break;
            }

        }

        return $filePath;
    }

    public function uploadFile($fileData, $type)
    {
        $app = JFactory::getApplication();
        /** @var $app JApplicationAdministrator */

        jimport('joomla.filesystem.archive');

        $uploadedFile = JArrayHelper::getValue($fileData, 'tmp_name');
        $uploadedName = JArrayHelper::getValue($fileData, 'name');
        $errorCode    = JArrayHelper::getValue($fileData, 'error');

        $destination = JPath::clean($app->get("tmp_path")) . DIRECTORY_SEPARATOR . JFile::makeSafe($uploadedName);

        $file = new Prism\File\File();

        // Prepare size validator.
        $KB       = 1024 * 1024;
        $fileSize = (int)$app->input->server->get('CONTENT_LENGTH');

        $mediaParams   = JComponentHelper::getParams("com_media");
        /** @var $mediaParams Joomla\Registry\Registry */

        $uploadMaxSize = $mediaParams->get("upload_maxsize") * $KB;

        // Prepare size validator.
        $sizeValidator = new Prism\File\Validator\Size($fileSize, $uploadMaxSize);

        // Prepare server validator.
        $serverValidator = new Prism\File\Validator\Server($errorCode, array(UPLOAD_ERR_NO_FILE));

        $file->addValidator($sizeValidator);
        $file->addValidator($serverValidator);

        // Validate the file
        if (!$file->isValid()) {
            throw new RuntimeException($file->getError());
        }

        // Prepare uploader object.
        $uploader = new Prism\File\Uploader\Local($uploadedFile);
        $uploader->setDestination($destination);

        // Upload the file
        $file->setUploader($uploader);
        $file->upload();

        $fileName = basename($destination);

        // Extract file if it is archive
        $ext = Joomla\String\String::strtolower(JFile::getExt($fileName));
        if (strcmp($ext, "zip") == 0) {

            $destFolder = JPath::clean($app->get("tmp_path")) . "/". $type;
            if (is_dir($destFolder)) {
                JFolder::delete($destFolder);
            }

            $filePath = $this->extractFile($destination, $destFolder);

        } else {
            $filePath = $destination;
        }

        return $filePath;
    }

    /**
     *
     * Import currencies from XML file.
     * The XML file is generated by the current extension ( Crowdfunding )
     *
     * @param string $file    A path to file
     * @param bool   $resetId Reset existing IDs with new ones.
     */
    public function importCurrencies($file, $resetId = false)
    {
        $xmlstr  = file_get_contents($file);
        $content = new SimpleXMLElement($xmlstr);

        if (!empty($content)) {

            // Check for existed currencies.
            $db    = $this->getDbo();
            $query = $db->getQuery(true);
            $query
                ->select("COUNT(*)")
                ->from($db->quoteName("#__crowdf_currencies", "a"));

            $db->setQuery($query);
            $result = $db->loadResult();

            if (!empty($result)) { // Update current currencies and insert newest.
                $this->updateCurrencies($content, $resetId);
            } else { // Insert new ones
                $this->insertCurrencies($content, $resetId);
            }
        }
    }

    protected function insertCurrencies($content, $resetId)
    {
        $items = array();

        $db = $this->getDbo();

        // Generate data for importing.
        foreach ($content as $item) {

            $title = Joomla\String\String::trim($item->title);
            $code  = Joomla\String\String::trim($item->code);
            if (!$title or !$code) {
                continue;
            }

            $id = (!$resetId) ? (int)$item->id : "null";

            $items[] = $id . "," . $db->quote($title) . "," . $db->quote($code) . "," . $db->quote(Joomla\String\String::trim($item->symbol)) . "," . (int)$item->position;
        }

        unset($content);

        $query = $db->getQuery(true);

        $query
            ->insert("#__crowdf_currencies")
            ->columns('id, title, code, symbol, position')
            ->values($items);

        $db->setQuery($query);
        $db->execute();

    }

    /**
     * Update the currencies with new columns.
     *
     * @param array $content
     */
    protected function updateCurrencies($content)
    {
        JLoader::register("CrowdfundingTableCurrency", JPATH_ADMINISTRATOR ."/components/com_crowdfunding/tables/currency.php");
        $db = $this->getDbo();

        foreach ($content as $item) {

            $code = Joomla\String\String::trim($item->code);

            $keys = array("code" => $code);

            $table = new CrowdfundingTableCurrency($db);
            $table->load($keys);

            if (!$table->get("id")) {
                $table->set("title", Joomla\String\String::trim($item->title));
                $table->set("code", $code);
                $table->set("position", 0);
            }

            // Update the symbol if missing.
            if (!$table->get("symbol") and !empty($item->symbol)) {
                $table->set("symbol", Joomla\String\String::trim($item->symbol));
            }

            $table->store();
        }

    }

    /**
     * Import locations from TXT or XML file.
     * The TXT file comes from geodata.org
     * The XML file is generated by the current extension ( Crowdfunding )
     *
     * @param string $file    A path to file
     * @param bool   $resetId Reset existing IDs with new ones.
     * @param int   $minPopulation Reset existing IDs with new ones.
     */
    public function importLocations($file, $resetId = false, $minPopulation = 0)
    {
        $ext = Joomla\String\String::strtolower(JFile::getExt($file));

        switch ($ext) {
            case "xml":
                $this->importLocationsXml($file, $resetId);
                break;
            default: // TXT
                $this->importLocationsTxt($file, $resetId, $minPopulation);
                break;
        }
    }

    protected function importLocationsTxt($file, $resetId, $minPopulation)
    {
        $content = file($file);

        if (!empty($content)) {
            $items = array();
            $db    = $this->getDbo();

            unset($file);

            $i = 0;
            $x = 0;
            foreach ($content as $geodata) {

                $item = mb_split("\t", $geodata);

                // Check for missing ascii characters name
                $name = Joomla\String\String::trim($item[2]);
                if (!$name) {
                    // If missing ascii characters name, use utf-8 characters name
                    $name = Joomla\String\String::trim($item[1]);
                }

                // If missing name, skip the record
                if (!$name) {
                    continue;
                }

                if ($minPopulation > (int)$item[14]) {
                    continue;
                }

                $id = (!$resetId) ? Joomla\String\String::trim($item[0]) : "null";

                $items[$x][] =
                    $id . "," . $db->quote($name) . "," . $db->quote(Joomla\String\String::trim($item[4])) . "," .
                    $db->quote(Joomla\String\String::trim($item[5])) . "," . $db->quote(Joomla\String\String::trim($item[8])) . "," . $db->quote(Joomla\String\String::trim($item[17]));

                $i++;
                if ($i == 500) {
                    $x++;
                    $i = 0;
                }
            }

            unset($content);

            foreach ($items as $item) {
                $query = $db->getQuery(true);

                $query
                    ->insert($db->quoteName("#__crowdf_locations"))
                    ->columns('id, name, latitude, longitude, country_code, timezone')
                    ->values($item);

                $db->setQuery($query);
                $db->execute();
            }
        }
    }

    protected function importLocationsXml($file, $resetId)
    {
        $xmlstr  = file_get_contents($file);
        $content = new SimpleXMLElement($xmlstr);

        if (!empty($content)) {
            $items = array();
            $db    = $this->getDbo();

            $i = 0;
            $x = 0;
            foreach ($content->location as $item) {

                // Check for missing ascii characters name
                $name = Joomla\String\String::trim($item->name);

                // If missing name, skip the record
                if (!$name) {
                    continue;
                }

                // Reset ID
                $id = (!empty($item->id) and !$resetId) ? Joomla\String\String::trim($item->id) : "null";

                $items[$x][] =
                    $id . "," . $db->quote($name) . "," . $db->quote(Joomla\String\String::trim($item->latitude)) . "," . $db->quote(Joomla\String\String::trim($item->longitude)) . "," .
                    $db->quote(Joomla\String\String::trim($item->country_code)) . "," . $db->quote(Joomla\String\String::trim($item->timezone));
                $i++;
                if ($i == 500) {
                    $x++;
                    $i = 0;
                }
            }

            unset($item);
            unset($content);

            foreach ($items as $item) {
                $query = $db->getQuery(true);

                $query
                    ->insert($db->quoteName("#__crowdf_locations"))
                    ->columns('id, name, latitude, longitude, country_code, timezone')
                    ->values($item);

                $db->setQuery($query);
                $db->execute();
            }
        }
    }

    /**
     * Import countries from XML file.
     * The XML file is generated by the current extension ( Crowdfunding )
     * or downloaded from https://github.com/umpirsky/country-list
     *
     * @param string $file    A path to file
     * @param bool   $resetId Reset existing IDs with new ones.
     */
    public function importCountries($file, $resetId = false)
    {
        $xmlstr  = file_get_contents($file);
        $content = new SimpleXMLElement($xmlstr);

        if (!empty($content)) {

            // Check for existed countries.
            $db    = $this->getDbo();
            $query = $db->getQuery(true);
            $query
                ->select("COUNT(*)")
                ->from($db->quoteName("#__crowdf_countries", "a"));

            $db->setQuery($query);
            $result = $db->loadResult();

            if (!empty($result)) { // Update current countries and insert newest.
                $this->updateCountries($content, $resetId);
            } else { // Insert new ones
                $this->insertCountries($content, $resetId);
            }
        }
    }

    protected function insertCountries($content, $resetId)
    {
        $items = array();

        $db = $this->getDbo();

        foreach ($content->country as $item) {

            $name = Joomla\String\String::trim($item->name);
            $code = Joomla\String\String::trim($item->code);
            if (!$name or !$code) {
                continue;
            }

            $id = (!$resetId) ? (int)$item->id : "null";

            $items[] =
                $id . "," . $db->quote($name) . "," . $db->quote($code) . "," . $db->quote($item->code4) . "," . $db->quote($item->latitude) . "," .
                $db->quote($item->longitude) . "," . $db->quote($item->currency) . "," . $db->quote($item->timezone);
        }

        unset($content);

        $columns = array("id", "name", "code", "code4", "latitude", "longitude", "currency", "timezone");

        $query = $db->getQuery(true);

        $query
            ->insert($db->quoteName("#__crowdf_countries"))
            ->columns($db->quoteName($columns))
            ->values($items);

        $db->setQuery($query);
        $db->execute();
    }

    /**
     * Update the countries with new columns.
     */
    protected function updateCountries($content)
    {
        JLoader::register("CrowdfundingTableCountry", JPATH_ADMINISTRATOR ."/components/com_crowdfunding/tables/country.php");
        $db = $this->getDbo();

        foreach ($content->country as $item) {

            $code = Joomla\String\String::trim($item->code);

            $keys = array("code" => $code);

            $table = new CrowdfundingTableCountry($db);
            $table->load($keys);

            if (!$table->id) {
                $table->name = Joomla\String\String::trim($item->name);
                $table->code = $code;
            }

            $table->code4     = Joomla\String\String::trim($item->code4);
            $table->latitude  = Joomla\String\String::trim($item->latitude);
            $table->longitude = Joomla\String\String::trim($item->longitude);
            $table->currency  = Joomla\String\String::trim($item->currency);
            $table->timezone  = Joomla\String\String::trim($item->timezone);

            $table->store();
        }
    }

    /**
     * Import states from XML file.
     * The XML file is generated by the current extension.
     *
     * @param string $file A path to file
     */
    public function importStates($file)
    {
        $xmlstr  = file_get_contents($file);
        $content = new SimpleXMLElement($xmlstr);

        $generator = (string)$content->attributes()->generator;

        switch ($generator) {

            case "crowdfunding":
                $this->importCrowdfundingStates($content);
                break;

            default:
                $this->importUnofficialStates($content);
                break;
        }
    }

    /**
     * Import states that are based on locations,
     * and which are connected to locations IDs.
     */
    protected function importCrowdfundingStates($content)
    {
        if (!empty($content)) {

            $states = array();
            $db     = $this->getDbo();

            // Prepare data
            foreach ($content->state as $item) {

                // Check for missing state
                $stateCode = Joomla\String\String::trim($item->state_code);
                if (!$stateCode) {
                    continue;
                }

                $id = (int)$item->id;

                $states[$stateCode][] = "(" . $db->quoteName("id") . "=" . (int)$id . ")";

            }

            // Import data
            foreach ($states as $stateCode => $ids) {

                $query = $db->getQuery(true);

                $query
                    ->update($db->quoteName("#__crowdf_locations"))
                    ->set($db->quoteName("state_code") . "=" . $db->quote($stateCode))
                    ->where(implode(" OR ", $ids));

                $db->setQuery($query);
                $db->execute();
            }

            unset($states);
            unset($content);

        }

    }

    /**
     * Import states that are based on not official states data,
     * and which are not connected to locations IDs.
     *
     * @param SimpleXMLElement $content
     *
     * @todo remove this in next major version.
     */
    protected function importUnofficialStates($content)
    {
        if (!empty($content)) {

            $states = array();
            $db     = $this->getDbo();

            foreach ($content->city as $item) {

                // Check for missing ascii characters title
                $name = Joomla\String\String::trim($item->name);
                if (!$name) {
                    continue;
                }

                $code = Joomla\String\String::trim($item->state_code);

                $states[$code][] = "(" . $db->quoteName("name") . "=" . $db->quote($name) . " AND " . $db->quoteName("country_code") . "=" . $db->quote("US") . ")";
            }

            foreach ($states as $stateCode => $cities) {

                $query = $db->getQuery(true);

                $query
                    ->update("#__crowdf_locations")
                    ->set($db->quoteName("state_code") . " = " . $db->quote($stateCode))
                    ->where(implode(" OR ", $cities));

                $db->setQuery($query);
                $db->execute();
            }

            unset($states);
            unset($content);
        }
    }

    public function removeAll($resource)
    {
        if (!$resource) {
            throw new InvalidArgumentException("COM_CROWDFUNDING_ERROR_INVALID_RESOURCE_TYPE");
        }

        $db = JFactory::getDbo();

        switch ($resource) {

            case "countries":
                $db->truncateTable("#__crowdf_countries");
                break;

            case "currencies":
                $db->truncateTable("#__crowdf_currencies");
                break;

            case "locations":
                $db->truncateTable("#__crowdf_locations");
                break;
        }
    }
}
